### ISSUE TITLE
Add support for Docker containers as tasks

### ISSUE THREAD

**Issue by sdegler** [twosigma/Cook#82] opened 2015-11-13 17:47 UTC
Hey, I’m looking at making cook + docker + custom executor +  application happen.   Right now this isn't quite possible because the /rawscheduler interface does not accept everything that is possible to express in a TaskInfo.
 
In my case this means being explicit about the executor (via an ExecutorInfo) and a ContainerInfo as well.   Fun fact: there are no less than 3 different places to specify a Containerinfo in the current TaskInfo as of 0.24.1.

I’m considering just creating a new (/uncooked?, /rawrawscheduler?, humorous name of your choosing) endpoint that basically just takes the json-ified TaskInfo.   The major incompatibility would be that there is a commandInfo replacing the simple command string.   This is actually useful to me but by introducting this as a new endpoint, I wouldn't be making a breaking API change.

Over time code will only talk to the newer endpoint, and the historical one can be retired.

This would have the advantage that the job submission interface would be more accessible  to other new users of the mesos ecosystem.   I think most examples of what could be input to marathon would then work with cook more or less directly as well.   

What do you think?

**Comment by dgrnbrg** [comment] 2015-11-13 18:48
I think that we should handle custom executors & docker containers as 2 separate projects. I'll discuss docker containers here.

The API could be changed by just adding the "container" subobject, just as marathon does. We only need to expose a limited form of port mappings (since we can specify them in-Docker, but they'll be auto-assigned on physical machine side), the image, whether to force-pull, and possibly the networking mode (although that may not be relevant).

The major design items will be:
- What the database schema will look like
- How TaskInfo generation will change
- How the API & validation logic will change

The biggest risk is potential conflicts to the scheduler rewrite (for fenzo) I'm currently engaged in.

**Comment by sdegler** [comment] 2015-11-13 20:41
1. I started looking at the code with just adding the container in mind and I have input  side mostly done by extending the schema just as you describe.   It way while I was in the process of that I though "isn't here some way I could generate the  schema from the TaskInfo in  mesos.proto and provide support for everything available".

2.  I looked at the taskinfo generation code but I haven't written any of that yet.

3. I don't care about port mappings for now, I would be adding them just for completeness.

4. I'm OK with host mode now, the only reason I'd allow it to be programmable would be for the sake of completeness.

5.  I though it would be clearer to pass an ExecutorInfo to the input, as this would be a better separation of concerns in the long run.   This also brought me back to the idea of adding new endpoint.

So are willing to look at some patches then ?

**Comment by dgrnbrg** [comment] 2015-11-13 20:44
Of course you can submit a PR so we can discuss the code there! I think it's important not to do too much in each feature, or else we could end up doing too much and struggling to get it all merged, or we could see an unanticipated regression.

**Comment by sdegler** [comment] 2015-11-13 21:29
Ok understood.

**Comment by wyegelwel** [comment] 2016-07-04 23:31
We merged docker support in #135

**Closed by wyegelwel** 2016-07-04 23:31 UTC
